site_name: Choreo
nav:
  - Welcome to Choreo: index.md
  - Installation: 01-installation/01_installation.md
  - Getting Started: 02-getting-started/01_getting_started.md
  - UserGuide: 
    - About: 03-userguide/01_about.md
    - Project: 03-userguide/02_project.md
    - Server: 03-userguide/03_server.md
    - Runner: 03-userguide/04_runner.md
    - Results: 03-userguide/05_results.md
    - Data changes: 03-userguide/06_datachanges.md
  - Developer Guide:
    - About: 04-devguide/01_about.md
    - APIs: 
      - CRD: 04-devguide/apis/01_crd.md
      - Generating CRDs with kubebuilder: 04-devguide/apis/02_kubebuilder.md
    - Reconcilers:
      - Reconciler: 04-devguide/reconcilers/01_reconciler.md
      - Reconciler Config: 04-devguide/reconcilers/02_config.md
      - GoTemplate: 04-devguide/reconcilers/03_gotemplate.md
      - Jinja2Template: 04-devguide/reconcilers/04_jinja2template.md
      - Starlark: 04-devguide/reconcilers/05_starlark.md
      - Libraries: 04-devguide/reconcilers/06_libraries.md
  - Examples/Tutorials:
    - About: 05-examples/01_about.md
  - Release Notes:
    - "0.0.14": 06-rn/0.0.14.md
    - "0.0.15": 06-rn/0.0.15.md
    - "0.0.16": 06-rn/0.0.16.md
    - "0.0.17": 06-rn/0.0.17.md
  - Community: 
    - Community: 07-community/01_about.md

site_author: Wim Henderickx
site_description: >-
  Choreo is a KRM orchestrator using  
# repository
repo_name: kform-dev/choreo-docs
repo_url: https://github.com/kform-dev/choreo-docs
site_url: "https://docs.choreo.kform.dev"
theme:
  name: material
  custom_dir: docs/overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs.sticky
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.tooltips
    #- header.autohide
    #- search.highlight
    #- search.share
    #- search.suggest
    #- toc.integrate
    - toc.follow
    
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Manrope
    code: Fira Mono
  icon:
    logo: fontawesome/solid/sitemap
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: assets/logos/Kform-logo-square.svg
  logo: assets/logos/Kform-logo-square.svg

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  
# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kform-dev
    # - icon: fontawesome/brands/discord
    #   link: https://discord.gg/fHCNahWR2T
    
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: kform
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.snippets:
      check_paths: true
      #dedent_subsections: true
      base_path:
        - ./
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde